### PR TITLE
Replace manual resource freeing with RAII

### LINKED ISSUE #243: Replace manual resource freeing with RAII
There are currently a few places where manual resource freeing is being done.
Leaving this to the programmer can cause memory leaks.

Example - `mpz_t` resource:
```cpp
std::string ThresholdUtils::convertHexToDec( const std::string& hex_str ) {
    mpz_t dec;
    mpz_init( dec );

    std::string output;

    try {
        if ( mpz_set_str( dec, hex_str.c_str(), 16 ) == -1 ) {
            throw IncorrectInput( "Bad formatted hex string provided" );
        }

        char arr[mpz_sizeinbase( dec, 10 ) + 2];
        char* tmp = mpz_get_str( arr, 10, dec );
        output = tmp;

    } catch ( std::exception& e ) {
        mpz_clear( dec );
        throw IncorrectInput( e.what() );
    } catch ( ... ) {
        mpz_clear( dec );
        throw IncorrectInput( "Exception in convert hex to dec" );
    }

    mpz_clear( dec );
    return output;
}
```

We should move to custom wrapper that frees any resources automatically when destroyed

### PR DESCRIPTION
**Pull request by PropzSaladaz**
### Description

- Updated `mpz_t` manual resource init & freeing by using `mpz_class` instead
- Moved AES encryption/decryption out of `ThresholdUtils` into its own self-contained class - cleaner & more organized this way
    - Moved the respective tests from `unit_tests_util` to `unit_tests_te`
- Updated OpenSSL `EVP_*` functions to also use wrapper around its context for automatically free on each exception 

### Performance

- Changes should not impact performance. Only refactoring was done. No changes to algorithms.

Fixes #243

### CODE REVIEW

File: bls/bls.cpp [hunk 1]
```diff
@@ -98,23 +99,15 @@ std::pair< libff::alt_bn128_G1, std::string > Bls::HashtoG1withHint(
             point.X = x1;
             libff::alt_bn128_Fq temp_y = y1_sqr.sqrt();
 
-            mpz_t pos_y;
-            mpz_init( pos_y );
+            mpz_class y;
+            temp_y.as_bigint().to_mpz( y.get_mpz_t() );
 
-            temp_y.as_bigint().to_mpz( pos_y );
+            mpz_class neg_y = -y;
```
Comment (olehnikolaiev) [inline bls/bls.cpp]: please change to `neg_y = -y % q` here, otherwise the next line will always return false

File: tools/utils.cpp [hunk 2]
```diff
@@ -330,23 +326,15 @@ libff::alt_bn128_G1 ThresholdUtils::HashtoG1(
...
-
-            temp_y.as_bigint().to_mpz( pos_y );
-
-            mpz_t neg_y;
-            mpz_init( neg_y );
+            mpz_class y;
+            temp_y.as_bigint().to_mpz( y.get_mpz_t() );
 
-            ( -temp_y ).as_bigint().to_mpz( neg_y );
+            mpz_class neg_y = -y;
```
Comment (olehnikolaiev) [inline tools/utils.cpp]: please change to neg_y = -y % q here, otherwise the next line will always return false

**Review by olehnikolaiev — APPROVED** [review]

**Review by kladkogex — APPROVED** [review]
